#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook "chef-client"
cookbook "ssh_known_hosts"
cookbook "openssh"

cookbook "user",
    :git => "https://github.com/fnichol/chef-user.git"

cookbook "apt",
    :git => "git@github.com:opscode-cookbooks/apt.git"

cookbook "ntp",
    :git => "https://github.com/opscode-cookbooks/ntp.git"

cookbook "sudo",
    :git => "git@github.com:express42-cookbooks/sudo.git"

cookbook "lvm",
    :git => "https://github.com/opscode-cookbooks/lvm.git"

cookbook "base",
    :path => "site-cookbooks/base"

cookbook "sysctl",
    :git => "git@github.com:express42-cookbooks/sysctl.git"

cookbook "zabbix-server",
    :git => "git@github.com:express42-cookbooks/zabbix-server.git", :ref => 'zabbix2.2'

cookbook "partition",
    :git => "git@github.com:express42-cookbooks/partition.git"

cookbook "postgresql",
    :git => "git@github.com:express42-cookbooks/postgresql.git"

cookbook "zabbix",
    :path => "../zabbix" #git@github.com:express42-cookbooks/zabbix.git", :ref => 'zabbix2.2'

cookbook 'php',
    :git => "git@github.com:express42-cookbooks/php.git"

cookbook "nginx",
     :git => "git@github.com:evilmartians/chef-nginx.git"
